In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 기본 URL
base_url = "https://hoopshype.com/salaries/players/{}/"

# 시즌 범위 설정 (2001/02 형식)
seasons = [f"{year}/{year % 100 + 1:02d}" for year in range(2001, 2024)]

# 데이터 저장할 리스트
data = []

# 각 시즌에 대해 크롤링
for season in seasons:
    url = base_url.format(season)
    response = requests.get(url)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')

        # 선수 정보 테이블 찾기
        table = soup.find('table')

        if table:
            rows = table.find_all('tr')[1:]  # 첫 번째 행은 헤더이므로 제외

            for row in rows:
                cols = row.find_all('td')
                if len(cols) >= 3:  # 선수 이름과 급여가 있는지 확인
                    player_name = cols[1].text.strip()  # 선수 이름
                    salary = cols[2].text.strip()  # 급여

                    # 데이터 추가
                    data.append({
                        'Season': season,
                        'Player': player_name,
                        'Salary': salary
                    })
    else:
        print(f"Failed to retrieve data for {season}")

# DataFrame으로 변환
df = pd.DataFrame(data)

# 결과 출력
print(df)

# 데이터 저장 (CSV 파일로)
df.to_csv("nba_player_salaries_2001_2023.csv", index=False, encoding='utf-8-sig')

print(f"Total records: {len(df)}")

      Season         Player        Salary
0    2001/02        Phoenix  $232,811,962
1    2001/02      Minnesota  $209,509,778
2    2001/02         Boston  $205,136,427
3    2001/02      Milwaukee  $201,810,884
4    2001/02       New York  $196,157,742
..       ...            ...           ...
685  2023/24  Oklahoma City  $165,606,339
686  2023/24        Orlando  $159,439,435
687  2023/24    San Antonio  $156,537,603
688  2023/24           Utah  $149,019,923
689  2023/24        Detroit  $136,454,090

[690 rows x 3 columns]
Total records: 690

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 기본 URL
base_url = "https://hoopshype.com/salaries/players/{}/"

# 시즌 범위 설정
seasons = [f"{year}-{year + 1 % 100:02d}" for year in range(2001, 2024)]

# 데이터 저장할 리스트
data = []

# 각 시즌에 대해 크롤링
for season in seasons:
    url = base_url.format(season)
    response = requests.get(url)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')

        # 선수 정보 테이블 찾기
        table = soup.find('table')

        if table:
            rows = table.find_all('tr')[1:]  # 첫 번째 행은 헤더이므로 제외

            for row in rows:
                cols = row.find_all('td')
                if len(cols) >= 3:  # 선수 이름과 급여가 있는지 확인
                    player_name = cols[1].text.strip()  # 선수 이름
                    salary = cols[2].text.strip()  # 급여
                    salary2 = cols[3].text.strip()

                    # 데이터 추가
                    data.append({
                        'Season': season,
                        'Player': player_name,
                        'Salary': salary,
                        'Salary*': salary2
                    })

    else:
        print(f"Failed to retrieve data for {season}")

# DataFrame으로 변환
df = pd.DataFrame(data)

# 중복된 선수 이름이 없는지 확인 (예를 들어, 일부 선수가 여러 팀에 있을 수 있음)
df = df.drop_duplicates(subset=['Season', 'Player'])

# 결과 출력
print(df)

# 데이터 저장 (CSV 파일로)
df.to_csv("nba_salaries_2001_2023.csv", index=False, encoding='utf-8-sig')

print(f"Total records: {len(df)}")

          Season              Player       Salary      Salary*
0      2001-2002       Kevin Garnett  $22,400,000  $38,395,739
1      2001-2002    Shaquille O'Neal  $21,428,572  $36,730,618
2      2001-2002     Alonzo Mourning  $18,754,800  $32,147,518
3      2001-2002        Juwan Howard  $18,750,000  $32,139,290
4      2001-2002      Scottie Pippen  $18,083,564  $30,996,955
...          ...                 ...          ...          ...
11739  2023-2024      Jalen Crutcher      $64,343      $64,343
11740  2023-2024  Izaiah Brockington      $64,343      $64,343
11741  2023-2024      Taevion Kinsey      $64,343      $64,343
11742  2023-2024       Edmond Sumner      $40,459      $40,459
11743  2023-2024        Kaiser Gates      $35,389      $35,389

[11743 rows x 4 columns]
Total records: 11743

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 기본 URL
base_url = "https://hoopshype.com/salaries/players/{}/"

# 시즌 범위 설정
seasons = [f"{year}-{year + 1 % 100:02d}" for year in range(2001, 2002)]

# 데이터 저장할 리스트
data = []

# 각 시즌에 대해 크롤링
for season in seasons:
    url = base_url.format(season)
    response = requests.get(url)

    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')

        # 선수 정보 테이블 찾기
        table = soup.find('table')

        if table:
            rows = table.find_all('tr')[1:]  # 첫 번째 행은 헤더이므로 제외

            for row in rows:
                cols = row.find_all('td')
                if len(cols) >= 3:  # 선수 이름과 급여가 있는지 확인
                    player_name = cols[1].text.strip()  # 선수 이름
                    salary = cols[2].text.strip()  # 급여
                    salary2 = cols[3].text.strip()
                    # 데이터 추가
                    data.append({
                        'Season': season,
                        'Player': player_name,
                        'Salary': salary,
                        'Salary*': salary2
                    })

    else:
        print(f"Failed to retrieve data for {season}")

# DataFrame으로 변환
df = pd.DataFrame(data)

# 중복된 선수 이름이 없는지 확인 (예를 들어, 일부 선수가 여러 팀에 있을 수 있음)
df = df.drop_duplicates(subset=['Season', 'Player'])

# 결과 출력
print(df)

# 데이터 저장 (CSV 파일로)
df.to_csv("nba_salaries_2001_2023.csv", index=False, encoding='utf-8-sig')

print(f"Total records: {len(df)}")

        Season            Player       Salary      Salary*
0    2001-2002     Kevin Garnett  $22,400,000  $38,395,739
1    2001-2002  Shaquille O'Neal  $21,428,572  $36,730,618
2    2001-2002   Alonzo Mourning  $18,754,800  $32,147,518
3    2001-2002      Juwan Howard  $18,750,000  $32,139,290
4    2001-2002    Scottie Pippen  $18,083,564  $30,996,955
..         ...               ...          ...          ...
445  2001-2002      Charlie Bell      $89,292     $153,055
446  2001-2002     Tang Hamilton      $60,881     $104,355
447  2001-2002       Joe Crispin      $48,705      $83,485
448  2001-2002    Mike Penberthy      $28,405      $48,688
449  2001-2002   Dickey Simpkins      $26,190      $44,892

[450 rows x 4 columns]
Total records: 450